<grammar xmlns="http://relaxng.org/ns/structure/1.0"
    datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">

    <start>
        <ref name="bcg_matrix"/>
    </start>

    <define name="bcg_matrix">
        <element name="bcg_matrix">
            <optional><attribute name="string"/></optional>
            <attribute name="x_field"/>
            <attribute name="y_field"/>
            <optional><attribute name="x_label"/></optional>
            <optional><attribute name="y_label"/></optional>
            <optional><attribute name="label_field"/></optional>
            <optional><attribute name="size_field"/></optional>
            <optional><attribute name="color_field"/></optional>
            <optional><attribute name="x_midpoint"/></optional>
            <optional><attribute name="y_midpoint"/></optional>
            <optional><attribute name="quadrant_labels"/></optional>
            <optional><attribute name="js_class"/></optional>
        </element>
    </define>
</grammar>
