<grammar xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">

    <start><ref name="map"/></start>

    <define name="map">
        <element name="map">
            <optional><attribute name="string"/></optional>
            <optional><attribute name="res_partner"/></optional>
            <optional><attribute name="default_order"/></optional>
            <optional><attribute name="default_group_by"/></optional>
            <optional><attribute name="allow_resequence"/></optional>
            <optional><attribute name="routing"/></optional>
            <optional><attribute name="hide_name"/></optional>
            <optional><attribute name="hide_address"/></optional>
            <optional><attribute name="hide_title"/></optional>
            <optional><attribute name="panel_title"/></optional>
            <optional><attribute name="limit"/></optional>
            <optional><attribute name="js_class"/></optional>
            <optional><attribute name="__validate__"/></optional>
            <zeroOrMore>
                <element name="field">
                    <attribute name="name"/>
                    <optional><attribute name="string"/></optional>
                </element>
            </zeroOrMore>
        </element>
    </define>
</grammar>
