<grammar xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">

    <start><ref name="cohort"/></start>

    <define name="cohort">
        <element name="cohort">
            <optional><attribute name="string"/></optional>
            <optional><attribute name="date_start"/></optional>
            <optional><attribute name="date_stop"/></optional>
            <optional><attribute name="disable_linking"/></optional>
            <optional><attribute name="mode"/></optional>
            <optional><attribute name="timeline"/></optional>
            <optional><attribute name="interval"/></optional>
            <optional><attribute name="measure"/></optional>
            <optional><attribute name="sample"/></optional>
            <optional><attribute name="js_class"/></optional>
            <optional><attribute name="__validate__"/></optional>
            <zeroOrMore>
                <element name="field">
                    <attribute name="name"/>
                    <optional><attribute name="string"/></optional>
                    <optional><attribute name="invisible"/></optional>
                    <optional><attribute name="widget"/></optional>
                </element>
            </zeroOrMore>
        </element>
    </define>
</grammar>
